services:
    OpenCloud-Server:
        image: opencloud-server
        volumes:
            - type: volume
              source: FileStore
              target: /FileStore
        environment:
            - NODE_ENV=docker
            - AUTH_SECRET=${AUTH_SECRET}
            - DATABASE_URL=${DATABASE_URL}
        build:
            context: .
            dockerfile: Dockerfile
            target: deploy
        ports:
            - 8080:8080
volumes:
    FileStore:
